### ISSUE TITLE
generated C++ files create a scope problem 

### ISSUE THREAD

**Issue by Swannben** [jdeantoni/TCOS.lang#32]
### explanation

when you generate a C++ file that will use threads using compilerBackend.ts and cppGenerator sometimes the synchroniser or the lockingQueue can be created inside one of the thread they're meant to synchronize the end of. 

this creates a scope problem when the other thread that is supposed to synchronize with the first one refers to a queue that doesnt exist for it and when you try to get what's in the queue after the end of the thread. 

### potential solution 

we already have a list of all the created synchronizers' IDs we might be able to change it into a list of [ID, type] and create the synchronizers and the lists in the beginning of the main function of the generated file

**Comment by jdeantoni** [comment]
fixed in PR #33 
Was due to a syncEdge problem already fixed in main branch (in ccfglib.ts)
